/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register a new user (profile + credentials + session) in one transaction.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and open a session.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate tokens using the refresh token from the ``X-Refresh-Token`` header.
         */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Update the password for the logged-in user.
         */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recovery Config
         * @description Return the logged-in user's security question.
         */
        get: operations["get_recovery_config_api_auth_recovery_get"];
        put?: never;
        /**
         * Update Recovery Config
         * @description Set or update the logged-in user's security question and answer.
         */
        post: operations["update_recovery_config_api_auth_recovery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/recovery-question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lookup Recovery Question
         * @description Look up the security question configured for an email.
         */
        post: operations["lookup_recovery_question_api_auth_recovery_question_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Recovery Answer
         * @description Verify a security answer and return a password-reset token.
         */
        post: operations["verify_recovery_answer_api_auth_verify_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forgot Password
         * @description Trigger an OTP for password recovery. Always reports success.
         */
        post: operations["forgot_password_api_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Otp
         * @description Verify an OTP and return a password-reset token.
         */
        post: operations["verify_otp_api_auth_verify_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password-final": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Password Final
         * @description Reset the password with a valid reset token and open a fresh session.
         */
        post: operations["reset_password_final_api_auth_reset_password_final_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Return the current user's profile (PII fields excluded).
         */
        get: operations["get_me_api_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Me
         * @description Apply a partial update to the current user's profile.
         */
        patch: operations["update_me_api_users_me_patch"];
        trace?: never;
    };
    "/api/users/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Preferences
         * @description Return stored preferences the frontend reads post-login/refresh.
         *
         *     ``currency``/``country`` are persisted on the profile; ``timezone`` is the
         *     active request preference resolved by ``UserPreferencesMiddleware``.
         */
        get: operations["get_preferences_api_users_preferences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Countries
         * @description List countries with phone code, default currency and timezone.
         */
        get: operations["get_countries_api_metadata_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Currencies
         * @description List currencies for dropdowns.
         */
        get: operations["get_currencies_api_metadata_currencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metadata/constants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Constants
         * @description Return system reference constants for frontend synchronization.
         */
        get: operations["get_constants_api_metadata_constants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description Return the tag tree visible to the caller (system + user-owned).
         */
        get: operations["list_tags_api_tags__get"];
        put?: never;
        /**
         * Create Tag
         * @description Create a user-scoped tag.
         */
        post: operations["create_tag_api_tags__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Tag
         * @description Delete a user-owned tag. System tags are read-only.
         */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Tag
         * @description Update a tag. System tag name/type are read-only; aliases stay editable.
         */
        patch: operations["update_tag_api_tags__tag_id__patch"];
        trace?: never;
    };
    "/api/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description List transactions with optional grouping, sorting, and filtering.
         */
        get: operations["list_transactions_api_transactions__get"];
        put?: never;
        /**
         * Create Transaction
         * @description Create a manual transaction.
         */
        post: operations["create_transaction_api_transactions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{txn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transaction
         * @description Get a single transaction.
         */
        get: operations["get_transaction_api_transactions__txn_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Transaction
         * @description Delete a manual transaction; statement-imported rows are non-deletable.
         */
        delete: operations["delete_transaction_api_transactions__txn_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Transaction
         * @description Patch a transaction; statement-imported rows can only update notes/tags.
         */
        patch: operations["update_transaction_api_transactions__txn_id__patch"];
        trace?: never;
    };
    "/api/transactions/upload-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Statement
         * @description Upload file, parse, and stage rows as ``statement_pending``.
         */
        post: operations["upload_statement_api_transactions_upload_statement_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/upload-statement/{upload_id}/map-beneficiaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Map Beneficiaries
         * @description Resolve beneficiary text to ids on every pending row of the upload.
         */
        post: operations["map_beneficiaries_api_transactions_upload_statement__upload_id__map_beneficiaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/upload-statement/{upload_id}/categorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Categorize Statement
         * @description Run the categorization engine over the staged pending rows.
         */
        post: operations["categorize_statement_api_transactions_upload_statement__upload_id__categorize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/upload-statement/{upload_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize Upload
         * @description Finalize an upload (``commit`` / ``rollback`` / ``set_misc``).
         */
        post: operations["finalize_upload_api_transactions_upload_statement__upload_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{txn_id}/manual-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manual Categorize Txn
         * @description Manually tag a pending/problematic statement transaction.
         */
        post: operations["manual_categorize_txn_api_transactions__txn_id__manual_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beneficiaries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Beneficiaries
         * @description List the user's visible beneficiaries (own + system-owned).
         */
        get: operations["list_beneficiaries_api_beneficiaries__get"];
        put?: never;
        /**
         * Create Beneficiary
         * @description Create a new beneficiary (with merchant or person detail).
         */
        post: operations["create_beneficiary_api_beneficiaries__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beneficiaries/check-alias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Alias
         * @description Check whether an alias (or beneficiary name) is globally unique.
         */
        get: operations["check_alias_api_beneficiaries_check_alias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beneficiaries/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Beneficiaries Route
         * @description Merge ``source_uid`` into ``target_uid``.
         */
        post: operations["merge_beneficiaries_route_api_beneficiaries_merge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beneficiaries/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Relationships
         * @description List the standard relationship types for a ``Person`` beneficiary.
         */
        get: operations["list_relationships_api_beneficiaries_relationships_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beneficiaries/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Beneficiary
         * @description Get a single beneficiary by uid.
         */
        get: operations["get_beneficiary_api_beneficiaries__uid__get"];
        put?: never;
        post?: never;
        /**
         * Delete Beneficiary
         * @description Delete a beneficiary (merchant/person rows cascade).
         */
        delete: operations["delete_beneficiary_api_beneficiaries__uid__delete"];
        options?: never;
        head?: never;
        /**
         * Update Beneficiary
         * @description Update a beneficiary; may switch merchant/person specialisation.
         */
        patch: operations["update_beneficiary_api_beneficiaries__uid__patch"];
        trace?: never;
    };
    "/api/categorization-rules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categorization Rules
         * @description List every categorization rule (system-owned first, then user-owned).
         */
        get: operations["list_categorization_rules_api_categorization_rules__get"];
        put?: never;
        /**
         * Create Categorization Rule
         * @description Create a categorization rule (one per beneficiary).
         */
        post: operations["create_categorization_rule_api_categorization_rules__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization-rules/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Categorization Rule
         * @description Patch a categorization rule. System rules accept notes/name updates.
         */
        put: operations["update_categorization_rule_api_categorization_rules__uid__put"];
        post?: never;
        /**
         * Delete Categorization Rule
         * @description Delete a user-owned categorization rule. System rules are read-only.
         */
        delete: operations["delete_categorization_rule_api_categorization_rules__uid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categorization-rules/re-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re Run Rules
         * @description Re-run every categorization rule across the user's statement transactions.
         */
        post: operations["re_run_rules_api_categorization_rules_re_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxation-rules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Taxation Rules
         * @description List effective taxation rules for the current user.
         */
        get: operations["list_taxation_rules_api_taxation_rules__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taxation-rules/{txn_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert Taxation Rule
         * @description Create or update the user's taxation rule for a txn_type.
         */
        put: operations["upsert_taxation_rule_api_taxation_rules__txn_type__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consumption-tax/bills/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Bills */
        post: operations["generate_bills_api_consumption_tax_bills_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consumption-tax/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bills */
        get: operations["list_bills_api_consumption_tax_bills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consumption-tax/bills/{bill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bill */
        get: operations["get_bill_api_consumption_tax_bills__bill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consumption-tax/bills/{bill_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pay Bill */
        post: operations["pay_bill_api_consumption_tax_bills__bill_id__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget-limits/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Budget Limits
         * @description List the user's budget limits (monthly only in MVP).
         */
        get: operations["list_budget_limits_api_budget_limits__get"];
        put?: never;
        /**
         * Upsert Budget Limit
         * @description Create or update a monthly budget limit for one tag.
         */
        post: operations["upsert_budget_limit_api_budget_limits__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget-limits/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Budget Status
         * @description Detailed merged budget/tracker/limits report for the active month.
         */
        get: operations["get_budget_status_api_budget_limits_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AliasCheckResponse */
        AliasCheckResponse: {
            /** Alias */
            alias: string;
            /** Unique */
            unique: boolean;
        };
        /** AnswerVerifyRequest */
        AnswerVerifyRequest: {
            /**
             * Email Id
             * Format: email
             */
            email_id: string;
            /** Answer */
            answer: string;
        };
        /** BeneficiaryCreate */
        BeneficiaryCreate: {
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[] | null;
            /**
             * Beneficiary Type
             * @enum {string}
             */
            beneficiary_type: "merchant" | "person";
            merchant?: components["schemas"]["MerchantDetailInput"] | null;
            person?: components["schemas"]["PersonDetailInput"] | null;
        };
        /** BeneficiaryMergeRequest */
        BeneficiaryMergeRequest: {
            /** Source Uid */
            source_uid: number;
            /** Target Uid */
            target_uid: number;
        };
        /** BeneficiaryResponse */
        BeneficiaryResponse: {
            /** Uid */
            uid: number;
            /** Name */
            name: string;
            /** Aliases */
            aliases?: string[] | null;
            /** Beneficiary Type */
            beneficiary_type?: string | null;
            merchant?: components["schemas"]["MerchantDetailResponse"] | null;
            person?: components["schemas"]["PersonDetailResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BeneficiaryUpdate */
        BeneficiaryUpdate: {
            /** Name */
            name?: string | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Beneficiary Type */
            beneficiary_type?: ("merchant" | "person") | null;
            merchant?: components["schemas"]["MerchantDetailInput"] | null;
            person?: components["schemas"]["PersonDetailInput"] | null;
        };
        /** Body_upload_statement_api_transactions_upload_statement_post */
        Body_upload_statement_api_transactions_upload_statement_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** BudgetLimitUpsert */
        BudgetLimitUpsert: {
            /** Tag Id */
            tag_id: number;
            /**
             * Budget Period
             * @default monthly
             */
            budget_period: string;
            /** Limit Amt */
            limit_amt: number;
            /** Penalty Rate */
            penalty_rate?: number | null;
        };
        /** CategorizationRuleCreate */
        CategorizationRuleCreate: {
            /** Name */
            name: string;
            /** Beneficiary Id */
            beneficiary_id: number;
            /** Tag Ids */
            tag_ids: number[];
            /** Notes */
            notes?: string | null;
        };
        /** CategorizationRuleUpdate */
        CategorizationRuleUpdate: {
            /** Name */
            name?: string | null;
            /** Beneficiary Id */
            beneficiary_id?: number | null;
            /** Tag Ids */
            tag_ids?: number[] | null;
            /** Notes */
            notes?: string | null;
        };
        /** CategorizeResponse */
        CategorizeResponse: {
            /** Upload Id */
            upload_id: number;
            /** Categorized Count */
            categorized_count: number;
            /** Problematic Count */
            problematic_count: number;
            /** Requires Confirmation */
            requires_confirmation: boolean;
            /** Problematic */
            problematic: Record<string, never>[];
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ConsumptionTaxBillGenerateRequest */
        ConsumptionTaxBillGenerateRequest: {
            /** Period Start */
            period_start: string;
            /** Period End */
            period_end: string;
        };
        /** CountriesResponse */
        CountriesResponse: {
            /** Countries */
            countries: components["schemas"]["CountryOption"][];
        };
        /** CountryOption */
        CountryOption: {
            /** Name */
            name: string;
            /** Country Code */
            country_code?: string | null;
            /** Default Currency */
            default_currency?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** CurrenciesResponse */
        CurrenciesResponse: {
            /** Currencies */
            currencies: components["schemas"]["CurrencyOption"][];
        };
        /** CurrencyOption */
        CurrencyOption: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /** Symbol */
            symbol?: string | null;
            /** Default Country */
            default_country?: string | null;
        };
        /** DeletedResponse */
        DeletedResponse: {
            /** Message */
            message: string;
        };
        /**
         * FinalizeRequest
         * @description Body for the finalize step.
         *
         *     ``decision`` ∈ {``commit``, ``rollback``, ``set_misc``}. Optional in the
         *     schema so an empty/missing value lands in the service layer and turns
         *     into a 400 with the same message the legacy router returned, instead of
         *     a Pydantic 422.
         */
        FinalizeRequest: {
            /** Decision */
            decision?: string | null;
        };
        /** FinalizeResponse */
        FinalizeResponse: {
            /** Status */
            status: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /**
             * Email Id
             * Format: email
             */
            email_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email Id
             * Format: email
             */
            email_id: string;
            /** Password */
            password: string;
        };
        /** ManualTagsRequest */
        ManualTagsRequest: {
            /** Tag Ids */
            tag_ids?: number[] | null;
        };
        /** ManualTagsResponse */
        ManualTagsResponse: {
            /** Status */
            status: string;
            /** Txn Id */
            txn_id: number;
            /** Tag Ids */
            tag_ids: number[];
        };
        /** MapBeneficiariesResponse */
        MapBeneficiariesResponse: {
            /** Status */
            status: string;
            /** Mapped Count */
            mapped_count: number;
        };
        /** MerchantDetailInput */
        MerchantDetailInput: {
            /** Category */
            category?: string | null;
            /** Contact */
            contact?: string | null;
            /** Upi Id */
            upi_id?: string | null;
        };
        /** MerchantDetailResponse */
        MerchantDetailResponse: {
            /** Category */
            category?: string | null;
            /** Contact */
            contact?: string | null;
            /** Upi Id */
            upi_id?: string | null;
        };
        /** MergeResponse */
        MergeResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
        };
        /** OTPVerifyRequest */
        OTPVerifyRequest: {
            /**
             * Email Id
             * Format: email
             */
            email_id: string;
            /** Otp */
            otp: string;
        };
        /** PersonDetailInput */
        PersonDetailInput: {
            /** Relationship Type */
            relationship_type?: string | null;
            /** Phone */
            phone?: string | null;
            /** Upi Id */
            upi_id?: string | null;
        };
        /** PersonDetailResponse */
        PersonDetailResponse: {
            /** Relationship Type */
            relationship_type?: string | null;
            /** Phone */
            phone?: string | null;
            /** Upi Id */
            upi_id?: string | null;
        };
        /**
         * ProfileUpdate
         * @description Partial profile update — every field optional.
         */
        ProfileUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Dob */
            dob?: string | null;
            /** Contact */
            contact?: string | null;
            /** Country */
            country?: string | null;
            /** Currency */
            currency?: string | null;
        };
        /** RecoveryConfigResponse */
        RecoveryConfigResponse: {
            /** Questions */
            questions: components["schemas"]["RecoveryQuestionResponse"][];
        };
        /** RecoveryQuestionCreate */
        RecoveryQuestionCreate: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
        };
        /** RecoveryQuestionLookupRequest */
        RecoveryQuestionLookupRequest: {
            /**
             * Email Id
             * Format: email
             */
            email_id: string;
        };
        /**
         * RecoveryQuestionResponse
         * @description A single configured security question (no answer ever returned).
         */
        RecoveryQuestionResponse: {
            /** Uid */
            uid: number;
            /** Question */
            question: string;
        };
        /**
         * RegisterRequest
         * @description Integrated registration: profile + credentials + optional recovery Q&A.
         */
        RegisterRequest: {
            /**
             * Email Id
             * Format: email
             */
            email_id: string;
            /** Password */
            password: string;
            /** Security Question */
            security_question?: string | null;
            /** Security Answer */
            security_answer?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Dob */
            dob?: string | null;
            /** Contact */
            contact?: string | null;
            /** Country */
            country?: string | null;
            /** Currency */
            currency?: string | null;
        };
        /** ResetPasswordFinalRequest */
        ResetPasswordFinalRequest: {
            /** Reset Token */
            reset_token: string;
            /** New Password */
            new_password: string;
        };
        /** ResetTokenResponse */
        ResetTokenResponse: {
            /** Reset Token */
            reset_token: string;
        };
        /**
         * SystemConstantsResponse
         * @description System reference constants the frontend mirrors.
         */
        SystemConstantsResponse: {
            /** System User Id */
            SYSTEM_USER_ID?: number | null;
            /** Total Tag Id */
            TOTAL_TAG_ID: number;
            /** Miscellaneous Tag Id */
            MISCELLANEOUS_TAG_ID: number;
            /** Consumption Tax Tag Id */
            CONSUMPTION_TAX_TAG_ID: number;
            /** Taxable Txn Types */
            TAXABLE_TXN_TYPES: string[];
            /** Valid Tag Types */
            VALID_TAG_TYPES: string[];
            /** Valid Txn Types */
            VALID_TXN_TYPES: string[];
            /** Relationship Types */
            RELATIONSHIP_TYPES: string[];
        };
        /** TagCreate */
        TagCreate: {
            /** Tag Name */
            tag_name: string;
            /** Parent */
            parent?: number | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Tag Type */
            tag_type?: string | null;
        };
        /** TagEnvelope */
        TagEnvelope: {
            tag: components["schemas"]["TagNode"];
        };
        /** TagListResponse */
        TagListResponse: {
            /** Tags */
            tags: components["schemas"]["TagNode"][];
        };
        /**
         * TagNode
         * @description A single tag in the response tree.
         */
        TagNode: {
            /** Tag Id */
            tag_id: number;
            /** Tag Name */
            tag_name: string;
            /** Parent */
            parent?: number | null;
            /**
             * Aliases
             * @default []
             */
            aliases: string[];
            /** Tag Type */
            tag_type?: string | null;
            /** Created By */
            created_by?: number | null;
            /** Created At */
            created_at: string;
            /** Children */
            children?: components["schemas"]["TagNode"][] | null;
        };
        /** TagUpdate */
        TagUpdate: {
            /** Tag Name */
            tag_name?: string | null;
            /** Aliases */
            aliases?: string[] | null;
            /** Tag Type */
            tag_type?: string | null;
        };
        /**
         * TaxationRuleUpdate
         * @description Per-user override of a system taxation rule.
         *
         *     The router validates the path ``txn_type`` so it is not duplicated here.
         */
        TaxationRuleUpdate: {
            /** Tax Rate */
            tax_rate: number;
            /** Default Penalty Rate */
            default_penalty_rate: number;
        };
        /**
         * TokenResponse
         * @description Standard authentication response — tokens only, no PII.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Amount */
            amount: number;
            /** Debit Credit */
            debit_credit: string;
            /** Beneficiary Id */
            beneficiary_id?: number | null;
            /** Beneficiary Name */
            beneficiary_name: string;
            /**
             * Txn Date
             * @description Transaction date in ISO 8601 format (e.g. YYYY-MM-DDTHH:MM:SSZ)
             */
            txn_date: string;
            /** Notes */
            notes?: string | null;
            /** Tag Ids */
            tag_ids?: number[] | null;
        };
        /** TransactionUpdate */
        TransactionUpdate: {
            /** Amount */
            amount?: number | null;
            /** Debit Credit */
            debit_credit?: string | null;
            /** Beneficiary Id */
            beneficiary_id?: number | null;
            /** Beneficiary Name */
            beneficiary_name?: string | null;
            /**
             * Txn Date
             * @description Transaction date in ISO 8601 format
             */
            txn_date?: string | null;
            /** Notes */
            notes?: string | null;
            /** Tag Ids */
            tag_ids?: number[] | null;
        };
        /** UploadResponse */
        UploadResponse: {
            /** Upload Id */
            upload_id: number;
            /** Inserted Count */
            inserted_count: number;
            /** Requires Confirmation */
            requires_confirmation: boolean;
        };
        /**
         * UserEnvelope
         * @description Wrapper matching the ``{"user": {...}}`` response shape on ``/me``.
         */
        UserEnvelope: {
            user: components["schemas"]["UserPrivateResponse"];
        };
        /**
         * UserPreferencesResponse
         * @description Stored preferences the frontend reads post-login/refresh.
         */
        UserPreferencesResponse: {
            /** Currency */
            currency?: string | null;
            /** Country */
            country?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /**
         * UserPrivateResponse
         * @description The owner's view of their own profile.
         *
         *     Returned only by ``/api/users/me``. Carries every field the owner entered.
         */
        UserPrivateResponse: {
            /** User Id */
            user_id: number;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Email Id */
            email_id: string;
            /** Dob */
            dob?: string | null;
            /** Contact */
            contact?: string | null;
            /** Country */
            country?: string | null;
            /** Currency */
            currency?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recovery_config_api_auth_recovery_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryConfigResponse"];
                };
            };
        };
    };
    update_recovery_config_api_auth_recovery_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryQuestionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_recovery_question_api_auth_recovery_question_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryQuestionLookupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_recovery_answer_api_auth_verify_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_api_auth_verify_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OTPVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_final_api_auth_reset_password_final_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordFinalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
        };
    };
    update_me_api_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_users_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferencesResponse"];
                };
            };
        };
    };
    get_countries_api_metadata_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountriesResponse"];
                };
            };
        };
    };
    get_currencies_api_metadata_currencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrenciesResponse"];
                };
            };
        };
    };
    get_constants_api_metadata_constants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemConstantsResponse"];
                };
            };
        };
    };
    list_tags_api_tags__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
        };
    };
    create_tag_api_tags__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_api_tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_api_transactions__get: {
        parameters: {
            query?: {
                month?: string | null;
                year?: string | null;
                tag_id?: number | null;
                debit_credit?: "debit" | "credit";
                beneficiary_id?: number | null;
                group_by?: "merchant";
                sort_by?: "date" | "amount" | "frequency" | "total_amount";
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_api_transactions__post: {
        parameters: {
            query?: {
                rule_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_api_transactions__txn_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txn_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_api_transactions__txn_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txn_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_api_transactions__txn_id__patch: {
        parameters: {
            query?: {
                rule_id?: number | null;
            };
            header?: never;
            path: {
                txn_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_statement_api_transactions_upload_statement_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_statement_api_transactions_upload_statement_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_beneficiaries_api_transactions_upload_statement__upload_id__map_beneficiaries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapBeneficiariesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categorize_statement_api_transactions_upload_statement__upload_id__categorize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_upload_api_transactions_upload_statement__upload_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_categorize_txn_api_transactions__txn_id__manual_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txn_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualTagsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualTagsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_beneficiaries_api_beneficiaries__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeneficiaryResponse"][];
                };
            };
        };
    };
    create_beneficiary_api_beneficiaries__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeneficiaryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeneficiaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_alias_api_beneficiaries_check_alias_get: {
        parameters: {
            query: {
                alias: string;
                exclude_uid?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AliasCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merge_beneficiaries_route_api_beneficiaries_merge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeneficiaryMergeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relationships_api_beneficiaries_relationships_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_beneficiary_api_beneficiaries__uid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeneficiaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_beneficiary_api_beneficiaries__uid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_beneficiary_api_beneficiaries__uid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeneficiaryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeneficiaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categorization_rules_api_categorization_rules__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_categorization_rule_api_categorization_rules__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategorizationRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_categorization_rule_api_categorization_rules__uid__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategorizationRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_categorization_rule_api_categorization_rules__uid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    re_run_rules_api_categorization_rules_re_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_taxation_rules_api_taxation_rules__get: {
        parameters: {
            query?: {
                txn_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_taxation_rule_api_taxation_rules__txn_type__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                txn_type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxationRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_bills_api_consumption_tax_bills_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumptionTaxBillGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bills_api_consumption_tax_bills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_bill_api_consumption_tax_bills__bill_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bill_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pay_bill_api_consumption_tax_bills__bill_id__pay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bill_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_budget_limits_api_budget_limits__get: {
        parameters: {
            query?: {
                budget_period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_budget_limit_api_budget_limits__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetLimitUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_budget_status_api_budget_limits_status_get: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
